application/hermes/TestWebApp/Models/Group.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Reports = new HashSet<Report>();
            this.TravelContracts = new HashSet<TravelContract>();
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public byte level { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<TravelContract> TravelContracts { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}

application/hermes/TestWebApp/Models/Group_.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestWebApp.Models
{
    public partial class Group
    {
        [Required(ErrorMessage = "Group Name is required")]
        public string name_
        {
            get { return this.name; }
            set { this.name = value; }
        }

        [Required(ErrorMessage = "Support Group Level is required")]
        [Range(1, 4, ErrorMessage = "The field Support Group Level must be between 1 and 4")]
        public byte level_ 
        {
            get { return this.level; }
            set { this.level = value; }
        }

        public static List<SelectListItem> all_toSelectList(int? level = null, int? userId = null, HermesDBEntities hDesk = null)
        {
            hDesk = hDesk ?? new HermesDBEntities();

            List<SelectListItem> groups = new List<SelectListItem>();
            foreach(Group group in hDesk.Groups.Where(g => (level == null || g.level == level) &&
                                                           (userId == null || g.Users.Any(gu => gu.id == userId))
                                                     ))
            {
                groups.Add(new SelectListItem { Text = group.name + " (Level: " + group.level + ") ", Value = group.id.ToString() });
            }

            return groups;
        }

        public static IEnumerable<Group> getWithName_onUserLvl(string name, int userId, bool isFullName, HermesDBEntities hDesk = null)
        {
            hDesk = hDesk ?? new HermesDBEntities();

            // všechny groupy daného jména
            if (userId == 0)
            {
                if (isFullName)
                    return hDesk.Groups.Where(g => g.name == name);
                else
                    return hDesk.Groups.Where(g => g.name.Contains(name));
            }
            // groupy daného jména a na stejném lvl jako uživatel
            else
            {
                if (isFullName)
                    return hDesk.Groups.SqlQuery("SELECT dbo.Groups.* FROM dbo.Groups WHERE dbo.Groups.name = @p0 AND dbo.Groups.level IN (SELECT dbo.webpages_Roles.level FROM dbo.webpages_Roles JOIN dbo.webpages_UsersInRoles ON dbo.webpages_Roles.roleId = dbo.webpages_UsersInRoles.roleId WHERE dbo.webpages_UsersInRoles.userId = @p1);", name, userId);
                else
                    return hDesk.Groups.SqlQuery("SELECT dbo.Groups.* FROM dbo.Groups WHERE dbo.Groups.name LIKE @p0 AND dbo.Groups.level IN (SELECT dbo.webpages_Roles.level FROM dbo.webpages_Roles JOIN dbo.webpages_UsersInRoles ON dbo.webpages_Roles.roleId = dbo.webpages_UsersInRoles.roleId WHERE dbo.webpages_UsersInRoles.userId = @p1);", String.Format("%{0}%", name), userId);
            }
        }
    }
}

application/hermes/TestWebApp/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestWebApp.Models;
using WebMatrix.WebData;

namespace TestWebApp.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        public ActionResult Index(string msg = null)
        {
            ViewBag.Message = msg;
            HermesDBEntities hDesk = new HermesDBEntities();
            return View(hDesk.Groups.ToList());
        }

        [Authorize(Roles = "SuperUser")]
        public ActionResult Create(string msg = null)
        {
            ViewBag.Message = msg;
            Group group = new Group();
            return View(group);
        }
        [HttpPost]
        [Authorize(Roles = "SuperUser")]
        public ActionResult Create(Group model, string msg = null) //DO group model!!!!!
        {
            ViewBag.Message = msg;
            HermesDBEntities hDesk = new HermesDBEntities();

            try
            {
                if (ModelState.IsValid)
                {
                    hDesk.Groups.Add(model);
                    hDesk.SaveChanges();
                    return RedirectToAction("Details", new { @id = model.id });
                }
                else
                {
                    ViewBag.IsNotValid = true;
                    return View(model);
                }
            }
            catch (FormatException e)
            {
                ViewBag.message = e.Message;
                return View(model);
            }
        }

        public ActionResult Details(int id, string msg = null)
        {
            ViewBag.Message = msg;
            HermesDBEntities hDesk = new HermesDBEntities();
            Group group = hDesk.Groups.SingleOrDefault(g => g.id == id);
            if(group == null)
            {
                return RedirectToAction("NotFound", "Errors");
            }
            return View(group);
        }
        [HttpPost]
        [Authorize(Roles = "SuperUser")]
        public ActionResult Details(int id, FormCollection fc, string msg = null)
        {
            ViewBag.Message = msg;
            HermesDBEntities hDesk = new HermesDBEntities();
            var group = hDesk.Groups.Single(g => g.id == id);

            try
            {
                // name
                group.name = fc["name"];
                // users
                foreach (var user in TestWebApp.Models.User.inRole("SupportLevel", group.level, hDesk).ToList())
                {
                    bool inDatabase = group.Users.SingleOrDefault(u => u.id == user.id) != null;
                    bool input = fc["user_" + user.id] != "false";

                    if (inDatabase != input)
                    {
                        if (input)
                            group.Users.Add(user);
                        else
                            group.Users.Remove(user);
                    }
                }
              

                hDesk.SaveChanges();
                return RedirectToAction("Index", new { @id = id, @msg = "Group was successfully updated!" });
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
            }
            ViewBag.users = TestWebApp.Models.User.inRole("SupportLevel", group.level, hDesk);
            return View(group);
        }

        [Authorize(Roles = "SuperUser")]
        public ActionResult Remove(int id)
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            Group group = hDesk.Groups.Single(g => g.id == id);
            List<User> users = group.Users.ToList();
            foreach (User user in users)
            {
                group.Users.Remove(user);
            }
            hDesk.Groups.Remove(group);
            hDesk.SaveChanges();
            return RedirectToAction("Index", new { msg = "Group was removed!" });
        }

        public JsonResult GetGroups_onSameLvl(int id, string term)
        {
            List<string> groups = Group.getWithName_onUserLvl(term, id, false).Select(g => g.name).ToList();
            return Json(groups, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Exists(int id, string name)
        {
            bool valid = Group.getWithName_onUserLvl(name, id, true).Count() > 0;
            return Json(valid, JsonRequestBehavior.AllowGet);
        }
        public JsonResult getFiltered(int level = 0)
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            var groups = hDesk.Groups
                .Where(g => level == 0 || g.level == level)
                .OrderBy(g => g.name)
                .Select(g => new { g.id, g.name });
            return Json(groups, JsonRequestBehavior.AllowGet);
        }

        public ActionResult List_My_Groups()
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            User current_user = hDesk.Users.SingleOrDefault(u => u.id == WebSecurity.CurrentUserId);
            return View("Index",current_user.Groups.ToList());
        }
  
    }
}

application/hermes/TestWebApp/Views/Group/Create.cshtml
@model TestWebApp.Models.Group
@{
    ViewBag.Title = "Create New Support Group";
}

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">New Group Detail</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
        @if (ViewBag.Error != null)
        {
            <div class="alert alert-warning">@ViewBag.Error</div>
        }
        @using (@Html.BeginForm("Create", "Group", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                <label for="name" class="col-md-3 control-label ui-sortable">Name:</label>
                <div class="col-md-9 ui-sortable">
                    @Html.TextBoxFor(g => g.name_, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="level" class="col-md-3 control-label ui-sortable">Level:</label>
                <div class="col-md-9 ui-sortable">
                    @Html.TextBoxFor(g => g.level_, new { @type = "number", @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label for="level" class="col-md-3 control-label ui-sortable">Actions:</label>
                <div class="col-md-9 ui-sortable">
                    <button class="btn btn-success">Create Support Group</button>
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        }
            </div>
            <div class="col-md-6">
              

            </div>
      </div>
    </div>
</div>

application/hermes/TestWebApp/Views/Group/Details.cshtml
@using TestWebApp.Models;
@using System.Collections;
@model Group
@{
    ViewBag.Title = "";
    HermesDBEntities hDesk = new HermesDBEntities();
    User current_user = hDesk.Users.SingleOrDefault(u => u.id == WebSecurity.CurrentUserId);
}


    <div class="invoice">
        <div class="invoice-company">
            Blue travel, inc.
        </div>
        <div class="invoice-header">
            <div class="invoice-from">
                <small>pobočka</small>
                <address class="m-t-5 m-b-5">
                    <strong>@Model.name</strong><br>
                    Ulice<br>
                    Město, PSČ<br>
                    Telefon: (+420) 565-789-450<br>
                    Fax: (123) 456-7890
                </address>
            </div>
            <div class="invoice-to">
                <small>to</small>
                <address class="m-t-5 m-b-5">
                    <strong>Blue travel</strong><br>
                    Street Address<br>
                    City, Zip Code<br>
                    Phone: (123) 456-7890<br>
                    Fax: (123) 456-7890
                </address>
            </div>
            <div class="invoice-date">
                <small>Zřízena</small>
                <div class="date m-t-5">3. Března, 2012</div>
                <div class="invoice-detail">
                    číslo: 0000123DSS<br>
                    Pobočka
                </div>
            </div>
        </div>
        <div class="invoice-content">
            <div class="table-responsive">
                <table class="table table-invoice">
                    <thead>
                        <tr>
                            <th>Jméno uživatele</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (User u in Model.Users)
                        {
                            <tr>
                                <td>
                                    @Html.ActionLink(u.fullName, "Details/" + u.id, "User", null, new { @target = "_blank" })<br>
                                    <small>Zaměstnanec společnosti blue travel s.r.o.</small>
                                </td>
                                <td>@u.email</td>
                            </tr>

                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="invoice-footer text-muted">
            <p class="text-center m-b-5">
                BLUE TRAVEL
            </p>
            <p class="text-center">
                <span class="m-r-10"><i class="fa fa-globe"></i> bluetravel.net</span>
                <span class="m-r-10"><i class="fa fa-phone"></i> T:256-456-421</span>
                <span class="m-r-10"><i class="fa fa-envelope"></i> info@bluetravel.cz</span>
            </p>
        </div>
    </div>
    <!-- end invoice -->
<!--
<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Details</h4>
    </div>
    <div class="panel-body">

        <div class="form-group">
            <label for="name" class="col-md-1 control-label ui-sortable">Name:</label>
            <div class="col-md-2 ui-sortable">
                @Html.TextBox("Name", Model.name, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-1 control-label ui-sortable">Members:</label>
            <div class="col-md-4 ui-sortable">
                <table class="table">
                    <tbody>

    @foreach (User u in Model.Users)
    {
        <tr>
            <td>@Html.ActionLink(u.fullName, "Details/" + u.id, "User",null,new { @target = "_blank"})</td>
        </tr>

    }
                    </tbody>
                </table>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-md-1 control-label ui-sortable">Actions</label>
            <div class="col-md-4 ui-sortable">
                @if(current_user.webpages_Roles.SingleOrDefault(r=>r.RoleName == "SuperUser")!= null)
                { 
                <button class="btn btn-success">Update Support Group</button>
                @Html.ActionLink("Destroy", "Remove", new { @id = Model.id }, new { @class = "btn btn-danger" }) <span></span>
                }
                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
 </div>
    -->

application/hermes/TestWebApp/Views/Group/Index.cshtml
@using TestWebApp.Models;
@model List<Group>
@{
    HermesDBEntities hDesk = new HermesDBEntities();
    User current_user = hDesk.Users.SingleOrDefault(u=>u.id == WebSecurity.CurrentUserId);
    ViewBag.Title = "Pobočky";

    ViewBag.Parents = new LinkedList<KeyValuePair<string, string>>();
    ViewBag.Parents.AddLast(new KeyValuePair<string, string>("List", null));
}

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">List</h4>
    </div>
    <div class="panel-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Jméno pobočky</th>
                    <th>Počet uživatelů</th>
                </tr>
            </thead>
            @foreach (Group group in Model)
            {
                <tr>
                    <td>@Html.ActionLink(group.name, "Details", new { id = group.id })</td>
                    <td>@group.Users.Count</td>
                </tr>
            }
        </table>
        @if(current_user.webpages_Roles.SingleOrDefault(r=>r.RoleName == "SuperUser")!=null)
        {
            @Html.ActionLink("New", "Create", null, new { @class = "btn btn-primary" })
        }
    </div>
</div>