application/hermes/TestWebApp/Controllers/MonitoringController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestWebApp.Models;
using PagedList;
using PagedList.Mvc;
using WebMatrix.WebData;

namespace TestWebApp.Controllers
{
    [Authorize]
    public class MonitoringController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            ViewBag.Reports = hDesk.Reports;
            return View();
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [Authorize]
        public ActionResult Create(Report model)
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            User current_user = hDesk.Users.SingleOrDefault(u => u.id == WebSecurity.CurrentUserId);
            if (ModelState.IsValid)
            {
                Group group = hDesk.Groups.FirstOrDefault(g => g.name == model.groupName);

                IEnumerable<TravelContract> contractsForPeriod = group.TravelContracts.Where(tc => tc.CreatedAt >= model.PeriodFrom && tc.CreatedAt <= model.PeriodTo);

                Report report = new Report();
                report.GeneratedAt = DateTime.Now;
                report.Group = group;
                report.groupName = model.groupName;
                report.PeriodFrom = model.PeriodFrom;
                report.PeriodTo = model.PeriodTo;
                report.AmountOfMoneyForPeriod = 522;

                int amount = 0;
                foreach (TravelContract travelContract in contractsForPeriod)
                {
                    amount += travelContract.TravelEvent.Price * travelContract.Quantity;
                }
                report.AmountOfMoneyForPeriod = amount;
                hDesk.Reports.Add(report);
                hDesk.SaveChanges();
                return RedirectToAction("Index", new { msg = "Report úspěšně vygenerován" });
            }
            ViewBag.IsNotValid = true;
            return View(model);
        }

        public ActionResult Details(int id, string msg = null)
        {
            ViewBag.Message = msg;
            HermesDBEntities hDesk = new HermesDBEntities();
            Report report = hDesk.Reports.SingleOrDefault(r => r.Id == id);
            ViewBag.ReportContractsCount =
                report.Group.TravelContracts.Count(tc => tc.CreatedAt >= report.PeriodFrom && tc.CreatedAt <= report.PeriodTo).ToString();
            return View(report);
        }
    }
}

application/hermes/TestWebApp/Views/Monitoring/Create.cshtml
@using System.Security.Cryptography
@using TestWebApp.Models
@model TestWebApp.Models.Report
@{
    ViewBag.Title = "Vytvoř nový zájezd";
    HermesDBEntities hDesk = new HermesDBEntities();
    List<SelectListItem> Groups = new List<SelectListItem>();
    foreach (Group group in hDesk.Groups)
    {
        Groups.Add(new SelectListItem()
        {
            Text = group.name,
            Value = group.name
        });
    }
}
<script>
    $(document).ready(function () {
        $('#PeriodFrom_').datetimepicker();
        $('#PeriodTo_').datetimepicker();
    });
</script>

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Vygenerujte nový report</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                @using (@Html.BeginForm("Create", "Monitoring", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <div class="form-group">
                        <label for="Name" class="col-md-3 control-label ui-sortable">Od:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.PeriodFrom_, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.PeriodFrom_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Adress" class="col-md-3 control-label ui-sortable">Do:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.PeriodTo_, new {  @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.PeriodTo_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="Event" class="col-md-3 control-label ui-sortable">Vyberte Pobočku:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.DropDownListFor(model => model.groupName, Groups, new { @class = "form-control" })
                        </div>
                    </div>
                    <button class="btn btn-primary">Vygenerovat</button>
                }
            </div>
        </div>
    </div>
</div>

application/hermes/TestWebApp/Views/Monitoring/Index.cshtml
<meta http-equiv="content-type" content="text/html; charset=+" />@using TestWebApp.Models
@using PagedList.Mvc;
@using PagedList;
@{
    HermesDBEntities hDesk = new HermesDBEntities();
    ViewBag.Title = "Reporty";
}
<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Reporty</h4>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>Evidenční číslo reportu:</th>
                    <th>Jméno skupiny</th>
                    <th>Vygenerován dne</th>
                    <th>Od</th>
                    <th>Do</th>
                    <th>Příjem pobočky</th>
                </tr>
                @foreach (Report report in ViewBag.Reports)
                {
                    <tr>
                        <td>@Html.ActionLink(@String.Format("RP-{0}",report.Id), "Details/" + @report.Id)</td>
                        <td>@report.Group.name</td>
                        <td>@report.GeneratedAt</td>
                        <td>@report.PeriodFrom</td>
                        <td>@report.PeriodTo</td>
                        <td>@report.AmountOfMoneyForPeriod</td>
                    </tr>
                }
            </table>

        </div>
    </div>
</div>