application/hermes/TestWebApp/Models/Region.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int RT_minutes { get; set; }
        public int FT_minutes { get; set; }
        public double UTCtimeShift { get; set; }
        public string timeZoneId { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}

application/hermes/TestWebApp/Models/Region_.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestWebApp.Models
{
    public partial class Region
    {
        [Required]
        [Display(Name="Name")]
        [MaxLength(50)]
        public string name_ 
        {
            get { return this.name; }
            set { this.name = value; }
        }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Response Time must be greather than 0")]
        [Display(Name="Response Time")]
        public int RT_minutes_
        {
            get { return this.RT_minutes; }
            set { this.RT_minutes = value; }
        }


        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Fixed Time must be greather than 0")]
        [Display(Name = "Fixed Time")]
        public int FT_minutes_ 
        {
            get { return this.FT_minutes; }
            set { this.FT_minutes = value; }
        }


        [Required]
        [Display(Name = "Utc Time Shift")]
        public double UTCtimeShift_
        {
            get { return this.UTCtimeShift; }
            set { this.UTCtimeShift = value; }
        }


        public static List<SelectListItem> toSelectList(HermesDBEntities hDesk = null, User user = null)
        {
            hDesk = hDesk ?? new HermesDBEntities();
            List<SelectListItem> regions = new List<SelectListItem>();
            foreach (Region region in hDesk.Regions)
            {
                regions.Add(new SelectListItem {
                    Text = region.name, 
                    Value = region.id.ToString(),
                    Selected = (user != null && user.regionId == region.id) // selected is true if user region is equal to 'region'
                });
            }
            return regions;
        }

        public static List<SelectListItem> getTimeZones(Region region = null)
        {
            List<SelectListItem> tZones = new List<SelectListItem>();
            var timeZones = TimeZoneInfo.GetSystemTimeZones(); //get time zones
            foreach(var tz in timeZones) //value is total hour difference from UTC and text is the location exapmple
            {
                SelectListItem sli = new SelectListItem() {
                    Text = tz.DisplayName,
                    Value = tz.Id,
                    Selected = (region != null && region.timeZoneId == tz.Id) // selected is true if regions timezone is 'tz'
                };
                tZones.Add(sli); //add it to our list of  selecte list item
            }
            return tZones;//and finally return it :-)
        }

        public static IEnumerable<Region> all(HermesDBEntities hDesk = null)
        {
            hDesk = hDesk ?? new HermesDBEntities();
            return hDesk.Regions;
        }
    }
}

application/hermes/TestWebApp/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestWebApp.Models;
using PagedList;
using PagedList.Mvc;
namespace TestWebApp.Controllers
{
    [Authorize]
    public class RegionController : Controller
    {
        public ActionResult Index(int? page,string msg = null)
        {
            ViewBag.Message = msg;
            HermesDBEntities hDesk = new HermesDBEntities();
            ViewBag.Regions = hDesk.Regions.OrderBy(r => r.name).ToPagedList(page ?? 1, 10);
            return View();
        }

        [Authorize(Roles="SuperUser")]
        public ActionResult Create()
        {
            return View();
        }
        
        [Authorize(Roles = "SuperUser")]
        [HttpPost]
        public ActionResult Create(Region model)
        {
            if (ModelState.IsValid)
            {
                HermesDBEntities hDesk = new HermesDBEntities();

                TimeZoneInfo timeZone = TimeZoneInfo.GetSystemTimeZones().SingleOrDefault(t => t.Id == model.timeZoneId);
                Region newRegion = model;
                newRegion.UTCtimeShift = timeZone.BaseUtcOffset.TotalHours;
                hDesk.Regions.Add(newRegion);
                hDesk.SaveChanges();

                return RedirectToActionPermanent("Details", new { @id = newRegion.id, msg = "The region has been successfully created" });
            }
            else
            {
                ViewBag.IsNotValid = true;
                return View(model);
            }
        }

        public ActionResult Details(int id, string msg = null)
        {
            ViewBag.Message = msg;
            HermesDBEntities hDesk = new HermesDBEntities();
            Region region = hDesk.Regions.SingleOrDefault(r => r.id == id);
            return View(region);
        }

        [Authorize(Roles="SuperUser")]
        public ActionResult Edit(int id)
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            Region region = hDesk.Regions.SingleOrDefault(r => r.id == id);
            return View(region);
        }

        [HttpPost]
        [Authorize(Roles = "SuperUser")]
        public ActionResult Edit(int id, Region model)
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            Region region = hDesk.Regions.SingleOrDefault(r => r.id == id);
            if (ModelState.IsValid)
            {
                TimeZoneInfo timeZone = TimeZoneInfo.GetSystemTimeZones().SingleOrDefault(t => t.Id == model.timeZoneId);
                region.FT_minutes = model.FT_minutes_;
                region.name = model.name_;
                region.RT_minutes = model.RT_minutes_;
                region.timeZoneId = model.timeZoneId;
                region.UTCtimeShift = timeZone.BaseUtcOffset.TotalHours;
                hDesk.SaveChanges();
                return RedirectToAction("Details/" + region.id, new { msg = "Region has been successfully updated" });
            }
            else
            {
                ViewBag.IsNotValid = true;
                return View(model);
            }
        }

        [Authorize(Roles = "SuperUser")]
        public ActionResult Remove(int id)
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            Region region = hDesk.Regions.SingleOrDefault(r => r.id == id);
            hDesk.Regions.Remove(region);
            hDesk.SaveChanges();

            return RedirectToAction("Index", new { msg = String.Format("Region {0} was removed.", region.name) });
        }
    }
}

application/hermes/TestWebApp/Views/Region/Create.cshtml
@model TestWebApp.Models.Region
@{
    ViewBag.Title = "Create New Region";
}

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">New Region Detail</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                @using (@Html.BeginForm("Create", "Region", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <div class="form-group">
                        <label for="name_" class="col-md-3 control-label ui-sortable">Name:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.name_, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.name_, "", new { @class="text-danger"})
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="RT_minutes_" class="col-md-3 control-label ui-sortable">Response time (In minutes):</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.RT_minutes_, new { @type = "number", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.RT_minutes_, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="FT_minutes_" class="col-md-3 control-label ui-sortable">Fix time (In minutes):</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.FT_minutes_, new { @type = "number", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.FT_minutes_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="timeZoneId" class="col-md-3 control-label ui-sortable">Utc time shift:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.DropDownListFor(model => model.timeZoneId, TestWebApp.Models.Region.getTimeZones(), new { @class= "form-control"})
                            @Html.ValidationMessageFor(model => model.UTCtimeShift_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="level" class="col-md-3 control-label ui-sortable">Actions:</label>
                        <div class="col-md-9 ui-sortable">
                            <button class="btn btn-success">Create Region</button>
                            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                        </div>
                    </div>
                }
            </div>
            <div class="col-md-6">


            </div>
        </div>
    </div>
</div>

application/hermes/TestWebApp/Views/Region/Details.cshtml
@using TestWebApp.Models;
@using System.Collections;
@model Region
@{
    ViewBag.Title = "Region Details";
    HermesDBEntities hDesk = new HermesDBEntities();
    User current_user = hDesk.Users.SingleOrDefault(u => u.id == WebSecurity.CurrentUserId);
}

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Details</h4>
    </div>
    <div class="panel-body">
        @using (@Html.BeginForm("Edit"+@Model.id, "Region", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                <label for="name" class="col-md-2 control-label ui-sortable">Name:</label>
                <div class="col-md-4 ui-sortable">
                    @Html.TextBox("Name", Model.name, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label ui-sortable">Utc time difference:</label>
                <div class="col-md-4 ui-sortable">
                    @Html.TextBox("UtcTimeDifference", Model.UTCtimeShift, new { type = "number", @class = "form-control", @disabled = "true" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label ui-sortable">Actions:</label>
                <div class="col-md-4 ui-sortable">
                    @if (current_user.webpages_Roles.SingleOrDefault(r => r.RoleName == "SuperUser") != null)
                    {
                        @Html.ActionLink("Edit", "Edit", new { @id = Model.id }, new { @class = "btn btn-primary" })
                        @(" ")
                        @Html.ActionLink("Remove", "Remove", new { @id = Model.id }, new { @class = "btn btn-danger" })
                    }
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        }
    </div>
</div>

application/hermes/TestWebApp/Views/Region/Edit.cshtml
@model TestWebApp.Models.Region
@{
    ViewBag.Title = "Edit Region";
}

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Edit Region</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                @using (@Html.BeginForm("Edit/"+@Model.id, "Region", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <div class="form-group">
                        <label for="name_" class="col-md-3 control-label ui-sortable">Name:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.name_, new {value = @Model.name, @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.name_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="RT_minutes_" class="col-md-3 control-label ui-sortable">Response time (In minutes):</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.RT_minutes_, new { value = @Model.RT_minutes,@type = "number", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.RT_minutes_, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="FT_minutes_" class="col-md-3 control-label ui-sortable">Fix time (In minutes):</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.FT_minutes_, new {value=@Model.FT_minutes, @type = "number", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.FT_minutes_, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="timeZoneId" class="col-md-3 control-label ui-sortable">Utc time shift:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.DropDownListFor(model => model.timeZoneId, TestWebApp.Models.Region.getTimeZones(@Model), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UTCtimeShift_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="level" class="col-md-3 control-label ui-sortable">Actions:</label>
                        <div class="col-md-9 ui-sortable">
                            <button class="btn btn-success">Edit Region</button>
                            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                        </div>
                    </div>
                }
            </div>
            <div class="col-md-6">


            </div>
        </div>
    </div>
</div>

application/hermes/TestWebApp/Views/Region/Index.cshtml
@using TestWebApp.Models
@using PagedList
@using PagedList.Mvc
@{
 HermesDBEntities hDesk = new HermesDBEntities();
 ViewBag.Title = "Regiony";
}
<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Regions</h4>
    </div>
    <div class="panel-body">
         <div class="table-responsive">
             <table class="table">
                 <tr>
                     <th>Name</th>
                     <th>Utc time difference</th>
                 </tr>
                 @foreach (Region region in ViewBag.Regions )
                 { 
                 <tr>
                     <td>@Html.ActionLink(@region.name,"Details/"+@region.id)</td>
                     <td>@region.UTCtimeShift</td>
                 </tr>
                 }
             </table>
             @Html.PagedListPager((IPagedList<Region>)ViewBag.Regions, page => Url.Action(ViewContext.RouteData.Values["action"].ToString(), new { page }))

         </div>
    </div>
</div>