application/hermes/TestWebApp/Controllers/ContactPersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestWebApp.Models;
using PagedList;
using PagedList.Mvc;

namespace TestWebApp.Controllers
{
    [Authorize]
    public class ContactPersonController : Controller
    {
        public ActionResult Index(int?page ,string msg=null)
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            ViewBag.Message = msg;
            ViewBag.Contacts = hDesk.Contacts.OrderBy(c => c.lastName + c.firstName).ToPagedList(page ?? 1, 10);
            return View();
        }

        [Authorize(Roles = "SuperUser")]
        public ActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Contact model)
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            if (ModelState.IsValid)
            {
                Contact contact = new Contact()
                {
                    firstName = model.fName_,
                    lastName = model.lName_,
                    address = model.address_,
                    email = model.email_,
                    phone = model.phone_
                };
                hDesk.Contacts.Add(contact);
                hDesk.SaveChanges();
                return RedirectToAction("Details/" + contact.id, new { msg = "Contact person has been successfully created" });
            }
            else
            {
                ViewBag.IsNotValid = true;
                return View(model);
            }
        }

        public ActionResult Details(int id,string msg = null)
        {
            ViewBag.Message = msg;
            HermesDBEntities hDesk = new HermesDBEntities();
            Contact contact = hDesk.Contacts.SingleOrDefault(c => c.id == id);
            if(contact == null)
                return RedirectToAction("NotFound" ,"Errors");
            return View(contact);
        }

        [Authorize(Roles = "SuperUser")]
        public ActionResult Edit(int id)
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            Contact contact = hDesk.Contacts.SingleOrDefault(c => c.id == id);
            if (contact == null)
                return RedirectToAction("NotFound", "Errors");

            else
            {
                return View(contact);
            }
        }

        [HttpPost]
        public ActionResult Edit(Contact model)
        {
            if (ModelState.IsValid)
            {
                HermesDBEntities hDesk = new HermesDBEntities();
                Contact contact = hDesk.Contacts.SingleOrDefault(c => c.id == model.id);
                contact.firstName = model.fName_;
                contact.lastName = model.lName_;
                contact.address = model.address_;
                contact.email = model.email_;
                contact.phone = model.phone_;
                hDesk.SaveChanges();
                return RedirectToAction("Details/" + contact.id, new { msg = "Contact person has been successfully updated" });
            }
            else
            {
                ViewBag.IsNotValid = true;
                return View(model);  
            }
        }

        [Authorize(Roles = "SuperUser")]
        public ActionResult Delete(int id)
        {
            HermesDBEntities hDesk = new HermesDBEntities();
            Contact contact = hDesk.Contacts.SingleOrDefault(c => c.id == id);
             if (contact == null)
                return RedirectToAction("NotFound", "Errors");
            foreach (Retailer retail in hDesk.Retailers)
            {
                if (retail.contactId == id)
                {
                    retail.Contact = null;
                }
            }
            hDesk.Contacts.Remove(contact);
            hDesk.SaveChanges();
            return RedirectToAction("Index", new { msg = "Contact person has been successfully removed" });
        }
        
    }
}

application/hermes/TestWebApp/Views/ContactPerson/Create.cshtml
@model TestWebApp.Models.Contact
@{
    ViewBag.Title = "Create New Contact Person"; //customer group = dealer
}

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">New Contact Person Details</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                @using (@Html.BeginForm("Create", "ContactPerson", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <div class="form-group">
                        <label for="fName" class="col-md-3 control-label ui-sortable">First Name:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.fName_, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.fName_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                       <div class="form-group">
                        <label for="lName" class="col-md-3 control-label ui-sortable">Last Name:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.lName_, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.lName_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                   
                    
                     <div class="form-group">
                        <label for="address" class="col-md-3 control-label ui-sortable">Address:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.address_, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.address_, "", new { @class = "text-danger" })
                        </div>
                    </div> 
                    
                       <div class="form-group">
                        <label for="mail" class="col-md-3 control-label ui-sortable">Email:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.email_, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.email_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                       <div class="form-group">
                        <label for="phone" class="col-md-3 control-label ui-sortable">Phone number:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.phone_, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.phone_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="level" class="col-md-3 control-label ui-sortable">Actions:</label>
                        <div class="col-md-9 ui-sortable">
                            <button class="btn btn-success">Create Contact Person</button>
                            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                        </div>
                    </div>
                }
            </div>
            <div class="col-md-6">


            </div>
        </div>
    </div>
</div>

application/hermes/TestWebApp/Views/ContactPerson/Details.cshtml
@using TestWebApp.Models;
@using System.Collections;
@model Contact
@{
    ViewBag.Title = "Contact Person Details";
    HermesDBEntities hDesk = new HermesDBEntities();
    User current_user = hDesk.Users.SingleOrDefault(u => u.id == WebSecurity.CurrentUserId);
}

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Details</h4>
    </div>
    <div class="panel-body">
        @using (@Html.BeginForm("Edit" + @Model.id, "ContactPerson", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                <label for="fName" class="col-md-1 control-label ui-sortable">First Name:</label>
                <div class="col-md-2 ui-sortable">
                    @Html.TextBox("fName", Model.firstName, new { @class = "form-control", disabled = "true" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-1 control-label ui-sortable">Last Name:</label>
                <div class="col-md-2 ui-sortable">
                    @Html.TextBox("lName", Model.lastName, new { @class = "form-control", disabled = "true" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-1 control-label ui-sortable">Address:</label>
                <div class="col-md-2 ui-sortable">
                    @Html.TextBox("address", Model.address, new { @class = "form-control", disabled = "true" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-1 control-label ui-sortable">Email:</label>
                <div class="col-md-2 ui-sortable">
                    @Html.TextBox("email", Model.email, new { @class = "form-control", disabled = "true" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-1 control-label ui-sortable">Phone Number:</label>
                <div class="col-md-2 ui-sortable">
                    @Html.TextBox("phone", Model.phone, new { @class = "form-control", disabled = "true" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-1 control-label ui-sortable">Actions:</label>
                <div class="col-md-4 ui-sortable">
                    @if (current_user.webpages_Roles.SingleOrDefault(r => r.RoleName == "SuperUser") != null)
                    {
                        @Html.ActionLink("Edit", "Edit", new { @id = Model.id }, new { @class = "btn btn-primary" })<span></span>
                        @Html.ActionLink("Delete", "Delete", new { @id = Model.id }, new { @class = "btn btn-danger", onclick = "return confirm('Are you sure?');" })
                    }
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        }
    </div>
</div>

application/hermes/TestWebApp/Views/ContactPerson/Edit.cshtml
@model TestWebApp.Models.Contact
@{
    ViewBag.Title = "Edit Contact Person";
}

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Contact Person Details</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                @using (@Html.BeginForm("Edit/" + @Model.id, "ContactPerson", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <div class="form-group">
                        <label for="fName" class="col-md-3 control-label ui-sortable">First Name:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.fName_, new { value = Model.firstName, @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.fName_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="lName" class="col-md-3 control-label ui-sortable">Owner:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.lName_, new { value = Model.lastName, @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.lName_, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="manufacturer" class="col-md-3 control-label ui-sortable">Address:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.address_, new { value = Model.address, @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.address_, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="email" class="col-md-3 control-label ui-sortable">Email:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.email_, new { value = Model.email, @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.email_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                     <div class="form-group">
                        <label for="phone" class="col-md-3 control-label ui-sortable">Phone Number:</label>
                        <div class="col-md-9 ui-sortable">
                            @Html.TextBoxFor(model => model.phone_, new { value = Model.phone, @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.phone_, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="level" class="col-md-3 control-label ui-sortable">Actions:</label>
                        <div class="col-md-9 ui-sortable">
                            <button class="btn btn-success">Update Contact Person</button>
                            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                        </div>
                    </div>
                }
            </div>
            <div class="col-md-6">


            </div>
        </div>
    </div>
</div>

application/hermes/TestWebApp/Views/ContactPerson/Index.cshtml
@using TestWebApp.Models
@using PagedList
@using PagedList.Mvc
@{
    HermesDBEntities hDesk = new HermesDBEntities();
    ViewBag.Title = "Contact Persons";
}
<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Workstations</h4>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Email</th>
                    <th>Phone</th>
                </tr>
                @foreach (Contact c in ViewBag.Contacts)
                {
                    <tr>
                        <td>@Html.ActionLink(@c.firstName +" " + @c.lastName, "Details/" + @c.id)</td>
                        <td>@c.address</td>
                        <td>@c.email</td>
                        <td>@c.phone</td>
                    </tr>
                }
            </table>
            @Html.PagedListPager((IPagedList<Contact>)ViewBag.Contacts, page => Url.Action(ViewContext.RouteData.Values["action"].ToString(), new { page }))

        </div>
    </div>
</div>